### ISSUE TITLE
Off-by-one errors in Java lexer implemented in Java

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#136] opened 2021-12-17 15:49 UTC
I'm getting what looks like an off-by-one error in token positions. In [this source file](https://gist.github.com/vsajip/ef01149692e3fe0320a1fa136c6f3a85) being parsed, in this line:
```
                    retval.append("\\u"+s.substring(s.length()-4, s.length()));
```
I get the following token positions from the lexer implemented in Java:
```
STRING_LITERAL: "\\" 61 35 61 38
PLUS: + 61 39 61 39
IDENTIFIER: s 61 40 61 40
DOT: . 61 41 61 41
IDENTIFIER: substring 61 42 61 50
LPAREN: ( 61 51 61 51
IDENTIFIER: s 61 52 61 52
DOT: . 61 53 61 53
IDENTIFIER: length 61 54 61 59
LPAREN: ( 61 60 61 60
RPAREN: ) 61 61 61 61
MINUS: - 61 62 61 62
INTEGER_LITERAL: 4 61 63 61 63
COMMA: , 61 64 61 64
WHITESPACE:   61 65 61 65
IDENTIFIER: s 61 66 61 66
DOT: . 61 67 61 67
IDENTIFIER: length 61 68 61 73
LPAREN: ( 61 74 61 74
RPAREN: ) 61 75 61 75
RPAREN: ) 61 76 61 76
RPAREN: ) 61 77 61 77
SEMICOLON: ; 61 78 61 78
WHITESPACE: 
                 61 79 62 16
```
Notice how the `\\u` is reported as `\\` in the `STRING_LITERAL`. Conversely, with the lexer implemented in Python, I get this:
```
STRING_LITERAL: "\\u" 61 35 61 39
PLUS: + 61 40 61 40
IDENTIFIER: s 61 41 61 41
DOT: . 61 42 61 42
IDENTIFIER: substring 61 43 61 51
LPAREN: ( 61 52 61 52
IDENTIFIER: s 61 53 61 53
DOT: . 61 54 61 54
IDENTIFIER: length 61 55 61 60
LPAREN: ( 61 61 61 61
RPAREN: ) 61 62 61 62
MINUS: - 61 63 61 63
INTEGER_LITERAL: 4 61 64 61 64
COMMA: , 61 65 61 65
WHITESPACE:   61 66 61 66
IDENTIFIER: s 61 67 61 67
DOT: . 61 68 61 68
IDENTIFIER: length 61 69 61 74
LPAREN: ( 61 75 61 75
RPAREN: ) 61 76 61 76
RPAREN: ) 61 77 61 77
RPAREN: ) 61 78 61 78
SEMICOLON: ; 61 79 61 79
WHITESPACE: 
                 61 80 62 16
```
which looks correct; the `\\u` is correctly shown and the subsequent column positions agree with what I see in an editor.

**Comment by revusky** [comment] 2021-12-17 16:40
Drat. I guess there is a problem here. 

Well, one thing that needs to be investigated is whether the absolute offsets are wrong. You see, as I describe in the recent blog posts, internally, the tokens only store absolute offsets, `beginOffset`, `endOffset` and that's inclusive/exclusive. I mean, if the absolute offsets are correct, but the line/column is wrong, then the bug is in translating the absolute offset to line/column. If the beginOffset/endOffset is incorrect, then the bug is something else. So maybe you could help me by answering that question.

In any case, we'll figure this out. This is probably a rather superficial glitch.

**Comment by revusky** [comment] 2021-12-17 17:47
Actually, I tried to investigate this a bit more and I think that the problem is here:
https://github.com/javacc21/javacc21/blob/master/src/ftl/java/Lexer.java.ftl#L733

That block of code, by the way, from line 724 to line 744, is the code that implements this JAVA_UNICODE_ESCAPE thing, you know, things like \u31FB or something like that. But it's kind of a weird thing, because the \u unicode escape applies if the number of consecutive backslashes preceding the u is odd, not if it is even. (I would say in passing that this kind of thing can be really sort of annoying to get right and is the kind of place where bugs do tend to lurk...)

But anyway, I think (I haven't really checked but you're in a better position to check!) that the problem is line 733, the `index++` is wrong. I suspect that if you comment that line out, everything will be fine. You see, it is incorrectly incrementing the index variable, which causes it to skip over the `u` in this case -- you know, the case here where we have an even number of backslashes before the u, so that we do NOT have a unicode escape...

Anyway, if you comment out that line and do a full rebuild, the problem may go away. (I think it will but I would not bet my life on this!)  I did comment out the line and run all tests and everything seems to work okay.

**Comment by vsajip** [comment] 2021-12-17 20:04
OK, I'll try that. Thanks!

**Comment by vsajip** [comment] 2021-12-17 20:32
I commented out that line and those problems went away, but there still seem to be some pertaining to TAB characters. For example, in [this file](https://gist.github.com/vsajip/080d3681bd78bd68b3dc3e1b6ce032e6) [not sure if uploading to Gist will have munged it], I get the following tokens in the Java version:
```
MULTI_LINE_COMMENT: /** 
      * @return the root node of the AST. It only makes sense to call
        * this after a successful parse. 
      */ 650 5 653 8
WHITESPACE: 
     653 9 654 4
```
vs. Python version:
```
MULTI_LINE_COMMENT: /** 
         * @return the root node of the AST. It only makes sense to call
         * this after a successful parse. 
         */ 650 5 653 11
WHITESPACE: 
     653 12 654 4
```
Now, in the source, lines 651-653 start with a single tab character. Are you counting these as 8 column positions? If so, then line 653 (and hence the multi-line comment) should end at column 11 as reported in Python, but the Java version reports 8 for the end column.

**Comment by revusky** [comment] 2021-12-18 12:34
It seems that the actual issue reported is resolved. Yeah, that was a mental lapse on my part, proving once again that I'm human after all. So I'll close this issue and I started a new issue for the TAB question.

**Closed by revusky** 2021-12-18 12:34 UTC
Labels: bug
