### ISSUE TITLE
FileLineMap should be stored in Grammar

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#44] opened 2021-01-22 11:07 UTC
I noticed the new last version of JavaCC21 stores in a static fields the FileLineMap. For memory leak, it's not a good idea (more for LSP context since Grammar instances is created each time user type something in the editor).

It should be nice to remove this static field and stores the FileLineMap in the Grammar instance.

In other words:

 * in Grammar:
 
```java
public class Grammar {
  
  private Map<String, FileLineMap> mapsByName= new HashMap<> ();

   public FileLineMap getFileLineMapByName(String name) {
        return mapsByName.get(name);
    }

}
```

 * in Node API:

```
default FileLineMap getFileLineMap() {
        return getGrammar().getFileLineMapByName(getInputSource());
    }
```

**Comment by revusky** [comment] 2021-01-22 20:01
Hi, Angel

First of all, I understand your concern about hanging onto references to FileLineMap. The reason I do what I do there is because I decided that Nodes should store an inputSource field that is a string. Now, regardless of anything else, that is necessary if only in order to be able to generate decent error messages! But it can also be used (in conjunction with the start/end location info) to get a copy of the original source that this Node came from. That's the idea (currently unused) but you see the code [here](https://github.com/javacc21/javacc21/blob/fault-tolerant/src/main/resources/templates/java/Node.java.ftl#L223) which, in getFileLineMap gets the original FileLineMap object from that static lookup. And then the default implementation of getSource()  just below that, once it looks up the FileLineMap object, can fish out the original source code by using the start/end location info that it stocks, right? I'm sure that this can be quite useful at times because if you are manipulating the tree, you can insert and remove Nodes or Tokens, but it can be useful to be able to get the reference source code from before any of that post-parse manipulation.

So, I decided to do things this way because I figured that actually storing a reference to the FileLineMap in any Node/Token object has a lot more potential for memory retention leaks than doing it this way! This way, at least we can wipe out all those references by simply calling clearFileLineMaps [here](https://github.com/javacc21/javacc21/blob/fault-tolerant/src/main/resources/templates/java/FileLineMap.java.ftl#L68)

Well there are more sophisticated things one can imagine, like using [weak references](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/WeakReference.html). A weak reference doesn't prevent the referent from being garbage collected. But, of course if the FileLineMap gets garbage collected but a Token is hanging onto a weak reference, then it needs to reread the file but if the contents of the file have changed, then the Node/Token is "stale". These are kinds of interesting concepts that...

Well, but anyway, when you say that this info should be stored in the Grammar, you are missing a key 

*The __generated__ Parser code has no Grammar object!* 

`com.javacc.Grammar` is a root object in the code *of the tool itself* that represents the root object of the tree that represents the parsed grammar file. BUT... once you generate the parser code, that *generated code* doesn't have a Grammar object! It has a XXXParser and a XXXLexer object and some other things like this.

(Actually, I see the source of your confusion about the Grammar object. The various Node/Token objects in the tool itself (JavaCC21 is written in JavaCC21!) all have a grammar field! See [here](https://github.com/javacc21/javacc21/blob/fault-tolerant/src/main/grammars/JavaCC.javacc#L175) and [here](https://github.com/javacc21/javacc21/blob/fault-tolerant/src/main/grammars/JavaCC.javacc#L752). You see, those are code injections in the JavaCC code itself so that BaseNode and Token (and all their descendants) have a grammar field. BUT... this is ONLY Node/Token objects used internally inside the code of the tool itself. The parsers you *generate*,a  the Node objects do NOT have a grammar field, because there is no Grammar object in the *generated* parser. It's very important to understand these things!)

But getting back to the issue of making everything garbage collectable, now that you bring this up, I think the solution almost certainly just to have more or less the same thing, but we use java.lang.ref.WeakReference and hold those weak references in the static hash lookup. You see, these XXXParser and XXXLexer objects are just disposable objects that are created and used a single time, so if XXXLexer holds a strong reference to the FileLIneMap object, once the XXXLexer object is garbage collected, then the FileLineMap is eligible for garbage collection as well. So that would pretty much address your concern, wouldn't it?

But as for the fact that there is no Grammar object in the *generated* code, you should really try to understand this point. It's very important moving forward to have absolute clarity about the code *of the tool* as opposed to the *code that the tool generates*! This whole problem of a tool that self-bootstraps and generates itself leads to these sorts of confusing things and you should not be ashamed that it is confusing. It's like recursion, for example, which the first time you start working with this, it is very confusing but comes more naturally. 

Actually, to tell the truth, both recursion and the tool self-bootstrapping confuses ME often enough even now! But that can also be a sign that it is time for me to get some sleep!

**Comment by angelozerr** [comment] 2021-01-23 08:13
> So, I decided to do things this way because I figured that actually storing a reference to the FileLineMap in any Node/Token object has a lot more potential for memory retention leaks than doing it this way! 

Yes and it's a good idea.

> The generated Parser code has no Grammar object!

Ok I see the problem now. But IMHO I think it's shame to have this static maps only because it's a generated process matter.

For me `FileLineMapProvider` concept belongs to the lexer, so I will stores this map in the lexer.

I will generate a new interface `FileLineMapProvider`:

```
public interface FileLineMapProvider {
    
    FileLineMap getFileLineMapByName(String name) {

}
```

and XXXLexer will implement this API.

I will set this FileLineMapProvider only for the root Node (ex ; for JavaCC, I will set this provider to the GramarFile instance)

The Node API  getFileLineMap will search the root node by using getParent to retrieve the root node and call the FileLineMapProvider stores in the GramarFile.

**Comment by revusky** [comment] 2021-01-28 08:05
I'm sorry to have taken so long to reply, but I've been occupied with other things. Finally, I was also a bit uncomfortable because I don't know how to put this very diplomatically, but I've decided to revert pretty much to what I had before and just close the issue. I don't think there is any value in working on this "problem". 

For one thing, it seems that you have some conceptual issue about all this. Somehow, you believe that there is much more at stake here than there really is. It doesn't really matter very much if the "root" node of the tree holds a reference to the FileLineMap or every last node does. You see, all of the nodes in the tree reference one another by a chain of parent/children references. From any one node, you can follow a chain of getParent/getChild links to traverse the entire tree. So, if you have a reference to the object in the root node (or any other node) it cannot be garbage collected unless the entire tree of nodes is garbage collectable. Well, the long and short of it is that entire tree of nodes AND everything any node refers to is garbage-collectable on an all-or-none basis anyway.  And the typical Node or Token object is going to have whatever memory footprint it has (plus or minus some bytes, but it doesn't make that much difference really) regardless. 

But there is a bigger problem in all of this, which is that you seem to want to define little projects for yourself that do not involve learning the core code -- or maybe I should say, really understanding *deeply* the overall system. And finally, I feel I have to put my foot down on this. I appreciate that you want to contribute. I really do. There are so many things to work on (far more than I can do alone) but the problem is this: *most meaningful things you can do  involve gaining a greater mastery over the system.* So I'm basically saying this:

*Any mini-project you set yourself as a task must be something that furthers your understanding of the overall system, the core code.*
 
At least somewhat... Now, come to think of it, when I say above "the core code" maybe that should be interpreted in a broader sense as just gaining a deeper understanding of how the overall system works. For example, if you set yourself the task of writing a grammar for TypeScript (you mentioned this as something desirable earlier, and I agree) this would not involve learning the core code of the tool, but it would surely involve getting to a level of being a "power-user" of the tool, at least. And that would certainly be a step in the right direction. But there does seem to be a real mental block, like you've built this up in your mind that you think that learning the code is much harder than it really is. And then the problem is that the longer this is allowed to continue, the bigger the mental block becomes.

But I've said as much about this as I'll say in public anyway. Probably I said too much, so if you want to pursue this conversation, we'll do it in private, I think.

**Closed by revusky** 2021-01-28 08:05 UTC
